---
# Apply latest style guide and new cops
AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  
# ignore block length in test code only
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
